### ISSUE TITLE
curl not found on Android 10

### ISSUE THREAD

**Issue by Biangkerok32** [Magisk-Modules-Alt-Repo/open_webview#1]
I'm try install online or offline ,get some error 🤔

I have try download file arm_SystemWebview.apk

Still some error,
What is wrong 🤔 ![Screenshot_20220930-062810](https://user-images.githubusercontent.com/48493593/193159566-76710db7-0341-486c-b93e-ce208c6b0846.png)

**Comment by spider1163** [comment]
Maybe try by installing a Busybox module first

**Comment by F3FFO** [comment]
This looks like an error due to the lack of the curl command. In the next release I will add the necessary binaries to avoid having to install additional modules like busybox!

**Comment by tay200k** [comment]
Yeah this is the same error I get when trying to install via foxes magisk module manager, if I try to install via magisk direct (busy box module installed) I just get the download error without the mention of curl.

**Comment by F3FFO** [comment]
Ok a fix will be available soon! I am currently working to be able to compile cUrl for all platforms.

**Comment by Biangkerok32** [comment]
![Screenshot_20221006-061338](https://user-images.githubusercontent.com/48493593/194181856-7d494659-d435-475e-9e66-11c76bad4914.png)

for a while i add curl manually. 
can you increase the curl download progress, so look more beautiful 🥰

**Comment by tay200k** [comment]
I managed to get the module installed by installing curl via  cross compiled binaries magisk module and rebooted. I still can't select bromite under webview implementation in Dev settings on Android 13. Just so you know every other way I tried like LSposed module anywebview and webview manager magisk module are also broke on Android 13.

**Comment by F3FFO** [comment]
Right now I don't have a device with Android 13 on which to test the module and debug. While doing various researches, I noticed that it is a fairly common problem on Android 13, I will try to stay informed to bring a working version as soon as possible. Anyway I just released the new version of the module that contains the cUrl binaries, let me know if it works now without having to install any additional module!

**Comment by tay200k** [comment]
> Right now I don't have a device with Android 13 on which to test the module and debug. While doing various researches, I noticed that it is a fairly common problem on Android 13, I will try to stay informed to bring a working version as soon as possible. Anyway I just released the new version of the module that contains the cUrl binaries, let me know if it works now without having to install any additional module!

Can confirm working installing via foxes magisk module manager without busybox or cross compiled binaries. tested and working on Android 11. (I went back to it as more mature platform for now)

I will go back to A13 if you add compatibility. Thank You!

**Comment by AAGaming00** [comment]
> Right now I don't have a device with Android 13 on which to test the module and debug. While doing various researches, I noticed that it is a fairly common problem on Android 13, I will try to stay informed to bring a working version as soon as possible. Anyway I just released the new version of the module that contains the cUrl binaries, let me know if it works now without having to install any additional module!

Still seems broken on 13, log looks normal but still using Android webview. Happy to help debug this via whatever means you prefer.

**Comment by F3FFO** [comment]
@bt4ibwem8 Please can you open a new issue or refer to another one that is already open instead of use a closed one
