### ISSUE TITLE
Bromite Fails to Download

### ISSUE THREAD

**Issue by secretServant** [Magisk-Modules-Alt-Repo/open_webview#10]
Currently it seems this module gets stuck at:

`Downloading BromiteWebview.apk...`

Could it have something to do with the Bromite project becoming defunct

**Comment by F3FFO** [comment]
@secretServant Thanks for the feedback but I just tried reinstalling the module and it didn't hang for me. It could be that your internet connection or connection to github servers has had some problem

**Comment by secretServant** [comment]
Interesting, disabling afwall (a firewall) entirely allows the apk download despite allowing foxmmm internet access prior

It definitely has to do with the 'curl' command in the installation method. I don't know why afwall would be blocking though
