### ISSUE TITLE
Support Mulch & Vanadium

### ISSUE THREAD

**Issue by secretServant** [Magisk-Modules-Alt-Repo/open_webview#11]
It seems as though the Bromite and un-googled Chromium project for android is falling behind releases of Chromium, it's been 3 months without a single update

DivestOS's Webview, Mulch, and Graphene OS's Webview, Vanadium, seem to be the only chromium webview forks keeping up to date

**Is your feature request related to a problem? Please describe.**
Add DivestOS WebView, Mulch
and
GrapheneOS WebView, Vanadium

**Describe the solution you'd like**
https://divestos.org/fdroid/official/
https://gitlab.com/divested-mobile/mulch
https://github.com/GrapheneOS/Vanadium/releases

**Comment by F3FFO** [comment]
HI @secretServant,

I've been thinking about it in the last few days and I share your proposal. So I started developing the Mulch implementation, the code is in the dev branch (it's currently in beta but at least it's working)

**Comment by bt4ibwem8** [comment]
What is main difference between them? Which one is faster? I just flashed Mulch...

**Comment by SkewedZeppelin** [comment]
@bt4ibwem8 
Vanadium is for GrapheneOS

Mulch is a fork of Vanadium meant to increase support for others.

**Comment by bt4ibwem8** [comment]
So Vanadium webview does not work properly on systems other than GOS?
