### ISSUE TITLE
Will you upload the source for the overlays? Having them in ZIPs is a bit shady.

### ISSUE THREAD

**Issue by xplshn** [Magisk-Modules-Alt-Repo/open_webview#15]
Also, what if you were malicious and decided to change those ZIPs to something illegitimate, like malware.

Also, which is more stable, and has more patches, Vanadium or Mulch, I read on Vanadium's github that Vanadium makes use of very specific features of GrapheneOS and so they won't release it for other Android distros. Have you had any problem with it? Is it safe to replace Webview with Vanadium?

**Comment by F3FFO** [comment]
I understand your doubt and honestly I took this approach to try to lighten the weight of the module, but I understand the doubt and I'll try to fix it in another way.

As for Vanadium vs. Mulch I would say that Vanadium is better for privacy and security, Mulch is still the best and most up-to-date alternative to Bromite. Personally, I currently have Vanadium on my device and I'm not experiencing any problems:
- Poco F2 PRO (lmi)
- Lineage OS 20

I had read that Vanadium was strictly compatible with GrapheneOS but I found a prebuilt version on GitLab (on the official GrapheneOS page) and I decided to personally test it on my devices (all with LineageOS) and I didn't have any problems so after a few days of test I decided to make this feature available to everyone.

Obviously I can't try all the devices with different ROMs I don't know what can happen, I don't know if it will work haha

**Comment by xplshn** [comment]
Okay then, great work! There used to be a project called Webview customizer that would let you change the features used by webview, like enabling or disabling javascript, crosssite cookies, an adblocker based on host files, it was cool but it seems to have vanished, I can't find it anywhere. Maybe you could do that with Xposed but I don't know, I'm not a developer.
