### ISSUE TITLE
Latest release crashes Magisk, then Android and leaves you without WebView

### ISSUE THREAD

**Issue by xplshn** [Magisk-Modules-Alt-Repo/open_webview#16]
I'm on Lineage 20
I updated from 2.1 to 2.2 and when it got the the installing webview step it hung Magisk and started to open and close the app repeatedly and I had to force a restart. It seems this is related to the bootloop issue. Check your latest release, or delete it and reupload when you fix it.

**Comment by F3FFO** [comment]
This is a bug that is not for everyone (for example I have never encountered it in my devices) so I don't see why I should delete the release to reload it, what I can do is try to understand the reason and make a new one release with bug fixes, so if you can give me some more details I can try to investigate:
- magisk version (whether it's the official topjohnwu version or what else)
- rom + android version
- device
- which webview did you try to install
- what other modules you have installed

Also have you tried installing the module without updating it? If yes, do you continue to have the same problem or is the problem only present if you upgrade from the previous version?
