### ISSUE TITLE
[BUG] Doesn't work on Pixel 7

### ISSUE THREAD

**Issue by HarriBuh** [Magisk-Modules-Alt-Repo/open_webview#18]
Google Pixel 7
Android 13
Magisk 25.2 (Huskydg's fork)

Whenever I install the app via Magisk and chose either of the featured Webviews (Vanadium & Mull, not using Bromite bc of security concerns), the overlay crashes/ won't work correctly after booting my phone. The screen stays black, although I am still able to click (recognised by visible fingertip). That's it.

I will have to restart the phone in safe mode (which is also possible as the pop-up still works) and manually switch back to standard Google Webview to get my phone back to working.

**Comment by F3FFO** [comment]
hi @HarriBuh , you are not the first one having this problem and having that version of magisk. My advice is to try to use the original version of Magisk to avoid compatibility problems. I'm leaving this issue open waiting for your update.
