### ISSUE TITLE
Overlay creation has failed on OOS

### ISSUE THREAD

**Issue by TrapStoner** [Magisk-Modules-Alt-Repo/open_webview#19]
Hello i have a OnePlus 7 Pro with OOS 11.0.9.1 and get overlay creation has failed error. What can i do to install this module?

**Comment by Vimt0** [comment]
Same here! Oneplus 7T Pro on Android 12 (OxygenOS 12.1)

**Comment by F3FFO** [comment]
I'm sorry to say that the problem is closely linked to an implementation choice of the ROM manufacturer and you can not do so much

**Comment by paour** [comment]
Same on OP8T with version 2.3.0. I previously had this module working (version 1.x).

**Comment by BigmenPixel0** [comment]
Realme C3 crDroid 9.8 & Redmi Note 9S LOS - the same problem.

**Comment by TrapStoner** [comment]
If anyone stumbles on this with a similar issue, i managed to install open webview (tried both vanadium and mulch) on my OP 7 Pro A11 Magisk Delta 27001 but every app relying on webview was crashing even the systemui took a looong time to open, [Mulch Webview Overlay by Alpha](https://github.com/A4Alpha/mulch-webview-overlay) was causing the same app crashes, so i tried doing it with Xposed and installed [AnyWebView](https://github.com/neoblackxt/AnyWebView) and what do you know i now have Mulch Webview!! In short: 

If you have app crashes OR can't install open webview due to overlay creation failure try to: 
1. Get lsposed - zygisk if you don't have it
2. Install [AnyWebView](https://github.com/neoblackxt/AnyWebView)
3, Install ANY webview you want i just downloaded Mulch from F-Droid
