### ISSUE TITLE
Update to newest Bromite Version 

### ISSUE THREAD

**Issue by HyperCriSiS** [Magisk-Modules-Alt-Repo/open_webview#2]
Hi,
Can you add the possibility for an update process to newest Bromite Version?

Best regards
Hyper

**Comment by F3FFO** [comment]
Hi @HyperCriSiS,
I don't see the need to always update to the latest version. The advantage you have by installing bromite through my module is that you can update bromite as a simple app using fdroid or by downloading the apk from the official repository!
