### ISSUE TITLE
Installing with KernelSU doesn't work (overlay creation failed), but with Magisk works like normal

### ISSUE THREAD

**Issue by th1nhhdk** [Magisk-Modules-Alt-Repo/open_webview#20]
![Screenshot_20230703-175009_KernelSU](https://github.com/Magisk-Modules-Alt-Repo/open_webview/assets/58503327/60b1b9ef-0fc5-4e18-8d12-5d870ed92e95)

**Comment by F3FFO** [comment]
Do not report bugs with unofficial magisks. I can't verify that they haven't introduced some bug that prevents my module from working.

**Comment by th1nhhdk** [comment]
KernelSU is different from Magisk, it's not a fork of Magisk

**Comment by F3FFO** [comment]
Yes I know but all that differs from magisk, including kernels other than official ones, I do not guarantee that the module continues to work!

**Comment by F3FFO** [comment]
@th1nhhdk See https://github.com/Magisk-Modules-Alt-Repo/open_webview/pull/23 maybe now it can work
