### ISSUE TITLE
[FEATURE] Add Thorium WebView

### ISSUE THREAD

**Issue by Emulond** [Magisk-Modules-Alt-Repo/open_webview#22]
![ThoriumLogo](https://github.com/Magisk-Modules-Alt-Repo/open_webview/assets/108662981/d58442dd-b065-4735-9130-2ad40e461cad)
# Thorium WebView — a blazingly fast and hardcoded WebView solution 

Please, add support for **Thorium WebView**.
It's a relatively **up-to-date** WebView which is **extremely light** and has outstanding performance.
[⚗️ Thorium — Android tree 🌿](https://github.com/Alex313031/Thorium-Android)

_Similar request: #11_

**Comment by F3FFO** [comment]
> ![ThoriumLogo](https://private-user-images.githubusercontent.com/108662981/270402706-d58442dd-b065-4735-9130-2ad40e461cad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0ODY3MTEsIm5iZiI6MTcwOTQ4NjQxMSwicGF0aCI6Ii8xMDg2NjI5ODEvMjcwNDAyNzA2LWQ1ODQ0MmRkLWIwNjUtNDczNS05MTMwLTJhZDQwZTQ2MWNhZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwM1QxNzIwMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMWJiMjA1NWQxMDAyMzBkYWE5ZGE3OWVhMDYyZGQxZTQ4ZDI4ODFhNzk4NzJjNzhjYWQ5ODAwNDIyOGRlMTRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-9sNnt4872OAa4AQIMPv8BSWsmGbQ4synGK_LvwUo4A)
> # Thorium WebView — a blazingly fast and hardcoded WebView solution
> 
> Please, add support for **Thorium WebView**. It's a relatively **up-to-date** WebView which is **extremely light** and has outstanding performance. [⚗️ Thorium — Android tree 🌿](https://github.com/Alex313031/Thorium-Android)
> 
> _Similar request: #11_

Added in the latest release ;)
