### ISSUE TITLE
Masterfile cant Install other Magisk Modules

### ISSUE THREAD

**Issue by TayLo1801** [Magisk-Modules-Alt-Repo/open_webview#3]
Hi There

i woud like to know if this Issue enqaunterd somone else

i'm new to rooting Andorind and have no Excperions with Magisk, how can i Fix this

Bromite System WebView is on Version 107.0.5304.114

Copying zip to temp directory! 
Unzip error

After Install of the Open_Webview in my Pixel 6 Pro Android 13 (Magisk Manager 25.2) i cant Install any other Modules Throug  Magisk.

Thanks in Advanced

**Comment by F3FFO** [comment]
Hi @TayLo1801 , sorry but I did not understand the origin of your problem: the installation of my module does not work and after you tried you are no longer able to install any other module?
