### ISSUE TITLE
Feature request: options in addition to volume keys

### ISSUE THREAD

**Issue by Iey4iej3** [Magisk-Modules-Alt-Repo/open_webview#33]
I do not have volume keys on my device (Onyx Boox Note Air 3C). I tried to use `input keyevent 24` to simulate, but it does not work. I hope that there are methods in addition to volume keys (e.g. accepting inputs from terminal).

**Comment by F3FFO** [comment]
Related to https://github.com/Magisk-Modules-Alt-Repo/open_webview/issues/42
