### ISSUE TITLE
"Missing overlay apk file" error message and installation failed

### ISSUE THREAD

**Issue by tinbilly** [Magisk-Modules-Alt-Repo/open_webview#34]
I installed this module on APatch (https://github.com/bmax121/APatch), but failed with an error message "missing overlay apk file".

My set-up is as follows:
- Device: moto g8 power
- ROM: crdroid v7.19
- Root solution: APatch release 10420 (https://github.com/bmax121/APatch)

Attached is my log file.
[APatch_install_log_2024-01-14-09-01-03.log](https://github.com/Magisk-Modules-Alt-Repo/open_webview/files/13930119/APatch_install_log_2024-01-14-09-01-03.log)

**Comment by F3FFO** [comment]
I'm sorry but I don't directly support apatch, I recommend you try other methods like [kernelsu](https://kernelsu.org/)
