### ISSUE TITLE
Setup failed

### ISSUE THREAD

**Issue by 1753135250** [Magisk-Modules-Alt-Repo/open_webview#35]
Please run 'e2fsck -fy /data/adb/modules_update/open_webview/overlay.img' to fix the filesystem
after the aborted resize operation.
/data/adb/modules_update/open_webview/overlay.img: 11/16 files (0.0% non-contiguous), 21/100 blocks
Resizing the filesystem on /data/adb/modules_update/open_webview/overlay.img to 96803840 (1k) blocks.
! Setup failed
- Done
How can i do?bro

**Comment by F3FFO** [comment]
> Please run 'e2fsck -fy /data/adb/modules_update/open_webview/overlay.img' to fix the filesystem after the aborted resize operation. /data/adb/modules_update/open_webview/overlay.img: 11/16 files (0.0% non-contiguous), 21/100 blocks Resizing the filesystem on /data/adb/modules_update/open_webview/overlay.img to 96803840 (1k) blocks. ! Setup failed
> 
>     * Done
>       How can i do?bro

It does not appear to be an error due to the module
