### ISSUE TITLE
Fails to download thorium

### ISSUE THREAD

**Issue by PistachioGuy** [Magisk-Modules-Alt-Repo/open_webview#41]
All other browsers work, but thorium just returns "Download failed".
Android 13, cpu architecture:arm

**Comment by PistachioGuy** [comment]
I think its because it tries to download "SystemWebView_arm.apk" when it should be downloading "SystemWebView_arm32.apk"

**Comment by F3FFO** [comment]
I'm sorry but I don't support anymore thorium so I will close this issue
