### ISSUE TITLE
Cromite Webview installation fails

### ISSUE THREAD

**Issue by HarriBuh** [Magisk-Modules-Alt-Repo/open_webview#48]
![magisk_install_log_2024-12-15T21.37.53.zip](https://github.com/user-attachments/files/18142019/magisk_install_log_2024-12-15T21.37.53.zip)

Google Pixel 7
Android 15
Rooted with Magisk 28101

Also tried Mulch Webview, no issues.

I'm also wondering what happened to the downloaded Cromite webview.. since it didn't install. Is the apk still somewhere on my phone?

**Comment by F3FFO** [comment]
Oh, sorry, my bad, I missed an if statement. If you're wondering what happened to the Chrome webview, it was downloaded to a temporary directory, so when the installation is finished (successfully or not) it gets deleted

**Comment by grm34** [comment]
> Another question: How will one be able to keep the different webviews up to date? Mulch offers his own repo on F-Droid, so it can be easily managed there, but what about the others?@F3FFO

You can follow github releases by adding `.atom` to the url (e.g. for cromite:  https://github.com/uazo/cromite/releases.atom).

There is also [obtainium](https://github.com/ImranR98/Obtainium) to track-only some apps.

**Comment by F3FFO** [comment]
> Another question: How will one be able to keep the different webviews up to date? Mulch offers his own repo on F-Droid, so it can be easily managed there, but what about the others?@F3FFO

As I said in the README this module doesn't directly update the webview but if you want to update it you have to reinstall the module. And as @grm34 said you can follow releases using app like obtainium

**Comment by F3FFO** [comment]
> ![magisk_install_log_2024-12-15T21.37.53.zip](https://github.com/user-attachments/files/18142019/magisk_install_log_2024-12-15T21.37.53.zip)
> 
> Google Pixel 7 Android 15 Rooted with Magisk 28101
> 
> Also tried Mulch Webview, no issues.
> 
> I'm also wondering what happened to the downloaded Cromite webview.. since it didn't install. Is the apk still somewhere on my phone?

I've just release a new version let me know if you can install Cromite

**Comment by grm34** [comment]
> I've just release a new version let me know if you can install Cromite

Fixed. Thanks for this awesome mod. Little confused that cromite webview still called `Android System Webview` but that's not your side 🙃

**Comment by F3FFO** [comment]
Yeah, I don't think is an error but a choise of the dev, however cromite webview has the same package name as as standard system webview
