### ISSUE TITLE
After enabling Bromite WebView

### ISSUE THREAD

**Issue by ssmohanv** [Magisk-Modules-Alt-Repo/open_webview#5]
I flash the module. After reboot, I enabled Bromite WebView after which my favourite Browser 1DM+. The error I am getting when opening 1DM+ is "java.lang.reflect.InvocationTargetException".

This may be because these guys are checking my bought license with Google WebView.

Except this, every other things are working as usual.

Thanks.

**Comment by F3FFO** [comment]
@ssmohanv Next time please don't spam
