### ISSUE TITLE
Webview crashes immediately due to missing .relro files

### ISSUE THREAD

**Issue by embeddedtofu** [Magisk-Modules-Alt-Repo/open_webview#8]
After installation webview should generate the 

/data/misc/shared_relro/libwebviewchromium64.relro
/data/misc/shared_relro/libwebviewchromium32.relro

files, which does not happen with this module. As such, any app depending on webview crashes.

As far as I can tell, the Bromite version isn't the issue as I tried that, even by modifying the module. Copying the original .relro files is useless, too.

LineageOS 18.1 (Android 11.0)

**Comment by F3FFO** [comment]
Hey @embeddedtofu , I understand the problem I have to investigate better about it. Have you tried to update the webView version and restart the device after installing the form?

**Comment by F3FFO** [comment]
I've done some tests and I can confirm that those files are not automatically generated when installing the module. In the next few days I'm going to work on it so if you have any suggestions on how to solve them, they are welcome. Anyway from the tests I understand that once the module is installed if you update bromite webview to the latest version those files are generated and you should be back to everything working!
