### ISSUE TITLE
Default webview in use

### ISSUE THREAD

**Issue by yephny** [Magisk-Modules-Alt-Repo/open_webview#9]
The module won't work in my case, just like WebView Manager.

I've installed the module and made sure that Bromite was installed by the module. I've restarted my phone, but I've yet to see any changes. In the Developer Settings, I still see only the default webview my system uses. When I go to Bromite's Webview DevTools, it says it's "not the system's curently selected WebView provider." Websites report I'm not on Bromite 106x Webview.

**Comment by F3FFO** [comment]
Thanks for your feedback @yephny, I need more information to investigate aboit your issue:
- model of your phone
- android version
- module version

**Comment by yephny** [comment]
v.2.0.
Samsung, Android 10 LineageOS.

**Comment by F3FFO** [comment]
Hi @yephny 

I made a number of improvements in the 2.1.0 release in which I tried to increase compatibility with other webviews.

Can you try the latest version and you can give me feedback if the problem has been solved?

**Comment by yephny** [comment]
Thanks, I'll test it out.

**Comment by yephny** [comment]
Sorry, I couldn't.
